services:
  focalboard:
    build:
      context: ..                   # bir üst dizin = proje kökü
      dockerfile: docker/Dockerfile # proje kökünden Dockerfile yolu
    container_name: focalboard
    depends_on:
      - focalboard-db
    ports:
      - "8000:8000"                 # Host 8000 → Container 8000
    volumes:
      - fbdata:/opt/focalboard/data
      - ../config/config.json:/opt/focalboard/config.json   # yalnızca bu dosyayı override ediyoruz
    networks:
      - proxy

  focalboard-db:
    image: postgres:latest
    container_name: focalboard-postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: boards
      POSTGRES_USER: boardsuser
      POSTGRES_PASSWORD: boardsuser-password
    networks:
      - proxy

volumes:
  fbdata:
  pgdata:

networks:
  proxy:
