services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: focalboard
    volumes:
      - fbdata:/opt/focalboard/data
    ports:
      - "3000:8000"        # host 3000 → container 8000
    environment:
      VIRTUAL_HOST: "focalboard.local"
      VIRTUAL_PORT: "8000"

volumes:
  fbdata:
